name: Run a pipeline

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Configure Python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"

    - name: Install libraries
      run: pip install azureml-core
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
#- name: run workflow 
#   run: python job.py
    
    - name: Install Azure ML Extention
      run: az extension add -n ml -y

    - name: Attach Workspace
      run: az configure --defaults group="churn-dev-rg" workspace="mlw-dev-mlops"
      
    - name: Run Pipeline
      run: az ml job create --file src/archive/empty-pipeline.yml --resource-group churn-dev-rg --workspace-name mlw-dev-mlops

