name: Run a pipeline

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: attach workspace
      run: az ml folder attach -w mlw-dev-mlops -g churn-dev-rg
    - name: run pipeline
      run: az ml run submit-pipeline -n myproject-pipeline -y archive/archive/empty-pipeline.yml
