# This is a basic workflow to help you get started with Actions

name: Challenge 3 - Run AML Pipeline on Push

# Controls when the workflow will run
on:
  push:
    branches:    
      - 'main'
      
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs AML Pipeline
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.8"
        
      - name: Install The Azure ML CLI package to be able to run the pipeline from CLI
        run: pip install azureml-core
        
      - name: Run the Python script with the pipeline
        run: python ./src/model/train.py


